create database dairy_project;

use dairy_project;


CREATE TABLE dairy_data (
    Location VARCHAR(100),
    Total_Land_Area DECIMAL(10,2),
    Number_of_Cows INT,
    Farm_Size VARCHAR(100),
    Date DATE,
    Product_ID INT,
    Product_Name VARCHAR(100),
    Brand VARCHAR(100),
    Quantity DECIMAL(10,2),
    Price_per_Unit DECIMAL(10,2),
    Total_Value DECIMAL(10,2),
    Shelf_Life INT,
    Storage_Condition VARCHAR(100),
    Production_Date DATE,
    Expiration_Date DATE,
    Quantity_Sold DECIMAL(10,2),
    Price_per_Unit_Sold DECIMAL(10,2),
    Approx_Total_Revenue DECIMAL(10,2),
    Customer_Location VARCHAR(100),
    Sales_Channel VARCHAR(100),
    Quantity_in_Stock DECIMAL(10,2),
    Min_Stock_Threshold DECIMAL(10,2),
    Reorder_Quantity DECIMAL(10,2)
);
-- 1 Total revenue generated by each product --
select product_name,sum(Approx_Total_Revenue) as total_revenue
from dairy_data
group by product_name
order by total_revenue desc;

-- 2 Brand with the highest total revenue -- 
select brand,sum(Approx_Total_Revenue) as total_revenue_by_brand
from dairy_data
group by brand
order by total_revenue_by_brand desc limit 1;

-- 3 Monthly revenue trend across all products --
select date_format(date, '%M') as months,sum(Approx_Total_Revenue) as total_revenue_by_months
from dairy_data
group by months
order by months ;

-- 4 Products below the minimum stock threshold --
SELECT Product_Name, Quantity_in_Stock, Min_Stock_Threshold
FROM dairy_data
WHERE Quantity_in_Stock < Min_Stock_Threshold;

-- 5 Total reorder quantity required per product--
select product_name,sum(Reorder_Quantity) as total_recordes
from dairy_data
group by product_name order by total_recordes desc;

-- 6 Which sales channel generates the most revenue --
select Sales_Channel, sum(Approx_Total_Revenue) as total_revenue
from dairy_data
group by sales_channel ;

-- 7 Top 5 customer locations by purchase volume --
select Customer_Location, sum(Quantity_Sold) as total_purchased 
from dairy_data
group by customer_location 
order by total_purchased desc limit 5;

-- 8 Average selling price per product --
select product_name, AVG(Price_per_Unit_Sold) as avg_selling_price
from dairy_data 
group by product_name ;

-- 9 Compare selling price with listed price -- 
select Product_name,price_per_unit as Listed_price,
Price_per_Unit_Sold as Selling_Price,
(Price_per_Unit_Sold - Price_per_Unit) as Difference
FROM dairy_data;

-- 10 Products with less than 10 days shelf life remaining --
select product_name,Expiration_Date,current_date() as today,
datediff(Expiration_Date,current_date()) as day_left 
from dairy_data 
where datediff(Expiration_Date,current_date()) < 10;

-- 11 Average shelf life by product category --
SELECT Product_Name, AVG(Shelf_Life) as  Avg_Shelf_Life
FROM dairy_data
GROUP BY Product_Name;

-- 12 Average number of cows per farm size category --
SELECT Farm_Size, AVG(Number_of_Cows) as Avg_Cows
FROM dairy_data
GROUP BY Farm_Size;

-- 13 Location with the largest total land area --
SELECT Location, sum(Total_Land_Area) as Total_Area
FROM dairy_data
GROUP BY Location
ORDER BY Total_Area DESC
LIMIT 1;

-- 14 Top 3 locations by average production quantity --
SELECT Location, avg(Quantity) as Avg_Production
FROM dairy_data
GROUP BY Location
ORDER BY Avg_Production DESC
limit 3;

-- 15 Calculate profit for each product --
SELECT Product_Name,
sum((Price_per_Unit_Sold - Price_per_Unit) * Quantity_Sold) as Profit
FROM dairy_data
GROUP BY Product_Name
ORDER BY Profit DESC;

-- 16 Most profitable brand overall-- 
SELECT Brand,
sum((Price_per_Unit_Sold - Price_per_Unit) * Quantity_Sold) as Profit_brand
FROM dairy_data
GROUP BY Brand
ORDER BY Profit_brand DESC LIMIT 1;

-- 17 Yearly revenue growth --
SELECT year(DATE) AS YEARS,
sum(Approx_Total_Revenue) as Total_Revenue
FROM Dairy_data
GROUP BY YEARS
ORDER BY YEARS;

-- 18 Best-selling product each year --
SELECT YEAR(Date) AS Year, Product_Name, SUM(Quantity_Sold) AS Total_Sold
FROM dairy_data
GROUP BY YEAR(Date), product_name
ORDER BY Year, Total_Sold DESC;

-- 19 Products that need immediate restock --
SELECT Product_Name, Quantity_in_Stock, Min_Stock_Threshold
FROM dairy_data
WHERE Quantity_in_Stock <= Min_Stock_Threshold;

-- 20 Identify expired products still in stock --
SELECT Product_Name, Expiration_Date, Quantity_in_Stock
FROM dairy_data
WHERE Expiration_Date < curdate()
AND Quantity_in_Stock > 0;

-- 21 Average shelf life per brand --
SELECT Brand, AVG(Shelf_Life) AS Avg_Shelf_Life
FROM dairy_data
GROUP BY Brand;

-- 22 Most popular product in each customer location --
SELECT Customer_Location, Product_Name, SUM(Quantity_Sold) AS Total_Sold
FROM dairy_data
GROUP BY Customer_Location, Product_Name
ORDER BY Customer_Location, Total_Sold DESC;









